[metadata]
name = akande
version = 0.0.4
author = Sebastian Rousseau
author_email = sebastian.rousseau@gmail.com
description = Akande: An OpenAI GPT-powered voice assistant.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/sebastienrousseau/akande
classifiers =
	Programming Language :: Python :: 3
	License :: OSI Approved :: Apache Software License
	Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9
install_requires =
	openai>=1.12.0
	pyaudio>=0.2.14
	python-dotenv>=1.0.1
	pyttsx4>=3.0.15
	reportlab>=4.1.0
	speechrecognition>=3.10.1
	cherrypy>=18.8.0
	pydub>=0.25.1

[options.entry_points]
console_scripts =
	akande = akande.__main__:run

[aliases]
test = pytest

[tool:pytest]
testpaths = tests

[wheel]
universal = 1
