# Copyright (C) 2026 Sebastien Rousseau.
#
# Licensed under the Apache License, Version 2.0 (the "License").
"""AI-disclosure helpers (EU AI Act Article 50).

Article 50 (binding 2 August 2026) requires that any user
interacting with an AI system be informed of that fact unless the
interaction is "obvious".  Voice and structured-briefing surfaces
are *not* obvious, so we emit a disclosure at the start of every
session when the active profile demands it.

This module is intentionally tiny: it returns the disclosure text
and decides whether to emit it.  The actual emission happens at the
edge — :class:`Akande` for voice sessions, the SSE route for the
Web UI — so callers can shape the disclosure to their medium (a
spoken utterance, an SSE event, a banner string).
"""

from __future__ import annotations

import logging

from akande.profiles import Profile, active_profile

logger = logging.getLogger(__name__)

DEFAULT_DISCLOSURE = (
    "You are talking to Àkàndé, an AI assistant. "
    "Responses are generated by a large language model and may "
    "be inaccurate.  Audio output is AI-generated."
)

SHORT_DISCLOSURE = (
    "You are interacting with Àkàndé, an AI assistant."
)


def get_disclosure_text(
    *,
    short: bool = False,
    custom: str | None = None,
) -> str:
    """Return the disclosure string to read aloud or display.

    Parameters
    ----------
    short:
        Use the spoken-utterance form (one sentence) suitable for a
        ~3 second TTS playback at the start of a voice session.
    custom:
        Override the built-in wording.  Used by operators with
        legal-approved alternatives.  We still preserve the
        "interacting with an AI" anchor by validating below.
    """
    if custom is not None:
        if "ai" not in custom.lower() and "agent" not in custom.lower():
            logger.warning(
                "Custom disclosure does not mention AI / agent "
                "— Article 50 requires the user be informed of "
                "AI interaction.  Falling back to the default.",
                extra={
                    "event": "Disclosure:CustomRejected",
                },
            )
            return SHORT_DISCLOSURE if short else DEFAULT_DISCLOSURE
        return custom
    return SHORT_DISCLOSURE if short else DEFAULT_DISCLOSURE


def should_disclose(profile: Profile | None = None) -> bool:
    """Return ``True`` when the active profile demands disclosure.

    Centralised so the policy check is identical across surfaces
    (CLI, TUI, Web UI, SSE).
    """
    p = profile if profile is not None else active_profile()
    return p.ai_disclosure


def log_disclosure_emitted(
    surface: str,
    *,
    text: str | None = None,
    correlation_id: str | None = None,
) -> None:
    """Record that a disclosure was shown / spoken.

    This is the audit-trail evidence of Article 50 compliance.
    Stays as a structured log entry rather than a separate file so
    operators can ship it through their existing log pipeline.
    """
    logger.info(
        "AI disclosure emitted",
        extra={
            "event": "Disclosure:Emitted",
            "correlation_id": correlation_id,
            "extra_data": {
                "surface": surface,
                "length": len(text or ""),
            },
        },
    )


def log_disclosure_suppressed(
    surface: str,
    reason: str,
    *,
    correlation_id: str | None = None,
) -> None:
    """Record an intentional non-disclosure (profile=internal)."""
    logger.warning(
        "AI disclosure suppressed",
        extra={
            "event": "Disclosure:Suppressed",
            "correlation_id": correlation_id,
            "extra_data": {
                "surface": surface,
                "reason": reason,
            },
        },
    )
